{{- if .Values.namespace.create -}}
{{- $namespace := include "ossm-smcp.namespace" . -}}
apiVersion: project.openshift.io/v1 
kind: Project
metadata:
  name: {{ $namespace }}
  labels:
    kubernetes.io/metadata.name: {{ $namespace }}
    {{- include "ossm-smcp.labels" . | nindent 4 }}
{{- if .Values.namespace.annotations -}}
  {{- with .namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
