{{- $namespace := include "ossm-smcp.namespace" . -}}
{{- $fullName := include "ossm-smcp.fullname" . -}}
{{- $testrollmember := include "ossm-smcp.tnsrollmember" . -}}
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default 
  namespace: {{ $namespace }}
spec:
  members:
    # a list of projects joined into the service mesh
{{- if $testrollmember }}
  - {{ $testrollmember }}
{{- end }}
{{- if .Values.members }}
    {{- range .Values.members }}
    {{- end }}
{{- end }}
